### ISSUE TITLE
Trouble executing test-suite after recreation with same name, using CLI

### ISSUE THREAD

**Issue by saratrajan** [akamai/cli-test-center#8]
# Description

Unable to execute a test-suite after we remove them using GUI (or CLI) and recreate with same name.

## Version

test-center version 0.1.1

## Steps to Reproduce

1. Delete/Remove an existing test-suite (say, `Sample Test Suite`)
2. Recreate it with same name (I used the import command to recreate from the .json file)
3. Run the below command 
`akamai test-center test --test-suite-name 'Sample Test Suite`
4. Error received as 
```shell
Getting test suite...... [OK]
The test suite with the name 'Sample Test Suite' could not be found. Run the 'test-suite list' command to get this value and try again.
```

**PS: I am able to run the recreated test-suite with its ID.**

**Comment by rakayada** [comment]
Hi @saratrajan 
We have identified this issue and the fix will be given in upcoming cli-test-center release.

**Comment by rakayada** [comment]
Hi @saratrajan , 

We have fixed this issue in the latest release, Please upgrade cli to latest version - https://github.com/akamai/cli-test-center/releases/tag/0.2.0

**Comment by rakayada** [comment]
Closing this issue as this has been already fixed in last release.
